[package]
name = "bitwi/meleegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Networker = "leifstout/networker@0.3.0"
RaycastHitbox = "ulferno/raycasthitbox@4.0.2"
React = "core-packages/react@0.0.1"
Fusion = "realdeedy/fusion@0.3.0"
Fastcast = "megamonsta2/fastcast@1.0.0"
Sift = "csqrl/sift@0.0.11"
Signal = "neonifieddev/signal@0.0.1"
Charm = "joelbrd/charm@1.0.5"
Dataservice = "leifstout/dataservice@0.3.2"
Janitor = "kineticwallet/janitor@1.17.0"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"