[package]
name = "leifs/genrojotree"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "cody-nelson/promise@4.0.1"
Roact = "jessekroeske/roact@1.4.2"
Sift = "csqrl/sift@0.0.11"
Rodux = "jessekroeske/rodux@3.0.0"
RoactRodux = "chipioindustries/roact-rodux@1.0.4"
Ripple = "littensy/ripple@0.9.3"
Signal = "sleitnick/signal@2.0.3"
Networker = "leifstout/networker@0.2.1"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Smartbone = "jakeywastaken/smartbone-2@0.5.2"
Charm = "joelbrd/charm@1.0.10"
ReactRodux = "solarhorizon/react-rodux@0.2.2"
ReactCharm = "littensy/react-charm@0.3.0"
Janitor = "kartzrbx/janitor@1.1.0"
ZonePlus = "essentiallyblue/zoneplus@3.2.2"
EZCameraShake = "arakodev/rbxcamerashaker@0.1.1"
ProfileStore = "vyon/profilestore@1.0.3"
RaycastHitbox = "ulferno/raycasthitbox@4.0.2"
BloodEngine = "megamonsta2/blood-engine@2.1.5"
FastCast = "megamonsta2/fastcast@1.0.0"
PartCache = "megamonsta2/partcache@1.1.3"