[package]
name = "bitwi/meleegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "ruizukun-dev/promise@4.0.3"
Networker = "leifstout/networker@0.3.0"
CastMelee = "ulferno/raycasthitbox@4.0.2"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"