-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	heart = "rbxassetid://109496938822520",
	heartDamaged = "rbxassetid://78414267956984",
	storageslot = "rbxassetid://128598260479730",
	storageslothighlighted = "rbxassetid://76528848573929",
}
