--!strict

local Utils = {}

Utils.Shared = require(script.Parent.Shared)
Utils.Config = require(script.Parent.Config)
Utils.State = require(script.Parent.State)
Utils.Cache = require(script.Parent.Cache)
Utils.Debug = require(script.Parent.Debug)
Utils.Net = require(script.Parent.Net)
Utils.Stream = require(script.Parent.Stream)
Utils.Data = require(script.Parent.Data)
Utils.Runtime = require(script.Parent.Runtime)
Utils.Render = require(script.Parent.Render)

return Utils