return {
	["PlatinumCoin"] = {
		name = "Platinum Coin",
		description = "A coin made of platinum. It is worth a lot of money!",
	},
	["GoldCoin"] = {
		name = "Gold Coin",
		description = "Ah yes, Gold!",
	},
	["SilverCoin"] = {
		name = "Silver Coin",
		description = "I mean, it's worth something. Sure is better than nothing!",
	},
	["CopperCoin"] = {
		name = "Copper Coin",
		description = "You're poor",
	},
	["Acorn"] = {
		name = "Acorn",
		description = "Your first ever crop! This can be planted to grow into a tree that produces more acorns!",
	},
	["Part"] = {
		name = "Part",
		description = "Loose crafting scrap salvaged from fallen enemies and equipment.",
	},
	["LifeCrystal"] = {
		name = "Life Crystal",
		description = "A condensed crystal that radiates restorative energy.",
	},
}
